### ISSUE TITLE
The read operation timed out Samsung QLED 

### ISSUE THREAD

**Issue by Toxminn** [roberodin/ha-samsungtv-custom#25]
Hello,

i can only Switch between apps. when i want to use keys the following error occurs:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1258, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 348, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 370, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 596, in media_play
    self.send_key("KEY_PLAY")
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 459, in send_key
    self.get_remote().control(key)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 430, in get_remote
    self._remote = self._remote_class(self._config)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote.py", line 12, in __init__
    self.remote = RemoteWebsocket(config)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote_websocket.py", line 42, in __init__
    self._read_response()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote_websocket.py", line 79, in _read_response
    response = self.connection.recv()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: The read operation timed out

**Comment by Toxminn** [comment]
Restarted my whole system... and it worked again :)
