### ISSUE TITLE
python 3.8 websocket timeout

### ISSUE THREAD

**Issue by terminet85** [roberodin/ha-samsungtv-custom#28]
`2020-01-04 19:22:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/media_player.py", line 558, in turn_off
    self.send_key("KEY_POWER")
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/media_player.py", line 459, in send_key
    self.get_remote().control(key)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/media_player.py", line 430, in get_remote
    self._remote = self._remote_class(self._config)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote.py", line 12, in __init__
    self.remote = RemoteWebsocket(config)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote_websocket.py", line 42, in __init__
    self._read_response()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungctl_qled/remote_websocket.py", line 79, in _read_response
    response = self.connection.recv()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 314, in recv
    opcode, data = self.recv_data()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 331, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 344, in recv_data_frame
    frame = self.recv_frame()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 378, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 453, in _recv
    return recv(self.sock, bufsize)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: The read operation timed out`

**Comment by terminet85** [comment]
websocket-client 0.57 is broken. Revert to 0.56 and it'll work
https://github.com/websocket-client/websocket-client/issues/595

**Comment by engn33r** [comment]
The issue mentioned above, websocket-client/websocket-client#595, has been closed. The issue should be resolved in the current development version of the websocket-client repository
