### ISSUE TITLE
TV not recognised when on a different VLAN

### ISSUE THREAD

**Issue by phoniclynx** [roberodin/ha-samsungtv-custom#30]
I've just decided to separate my network into different VLANs to separate out my IoT devices onto a different VLAN. If I put the TV onto the normal network (192.168.0.0/16) the scripts work beautifully fine, which is the same network as HA. However, if I put it on the IoT VLAN (172.16.0.1/24) I get errors in the logs and no TV device.

Below are the errors in the logs:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/config/custom_components/samsungtv_custom/media_player.py", line 510, in is_volume_muted
    self._muted = self._upnp.get_mute()
  File "/config/custom_components/samsungtv_custom/samsungctl_qled/upnp.py", line 50, in get_mute
    if (int(mute) == 0):
UnboundLocalError: local variable 'mute' referenced before assignment
```

**Comment by terminet85** [comment]
What version do you have of websocket-client?

**Comment by phoniclynx** [comment]
@terminet85 how do I know what version I am running? It's the latest docker of HA 100.6

**Comment by johntdyer** [comment]
Pretty sure I am facing the same issue here

**Comment by HeedfulCrayon** [comment]
Same issue here.  Ping works just fine.  I can also access the rest api response from my HA instance, but for some reason websockets don't seem to work for me either.
