### ISSUE TITLE
Problem with UN65KS850DFXZA (2016)

### ISSUE THREAD

**Issue by reefland** [roberodin/ha-samsungtv-custom#35]
First off, thanks for making this component. :)

Environment:
```arch	amd64
dev	false
docker	false
hassio	false
os_name	FreeBSD
os_version	11.2-STABLE
python_version	3.7.5
version	0.104.3
virtualenv	true
```

configuration.yaml:
```media_player:
  - platform: samsungtv_custom
    host: 192.168.2.234
    mac: !secret samsung_tv_mac
    port: 8001
    sourcelist: '{"FIOS": "KEY_HDMI1", "AcePC": "KEY_HDMI2"}'
    protocol: ws
```
Tested "protocol: ws" with port 8001 and 8002 not seeing a difference.
    
**What Works:**
Switch correctly reports state of "on and "off"
Sensor Media Input Source correctly reports between HDMI1/HDMI2

**Not Working:**
Sensor TV Volume - always shows 15
Sensor TV Channel - always blank
Sensor TV Media Playback Status - always unknown

Media Player entity - only shows status for power and always shows off, even when switch shows on.  Does not show anything else.  (not sure how it got the name "samsung_tv_remote).

Taken from DevTools States screen, it created:
```
media_player.samsung_tv_remote
State: off

Attributes:
source_list: FIOS,AcePC
friendly_name: Samsung TV Remote
supported_features: 20409

sensor.tv_samsung_8_series_65_media_input_source
State: HDMI1

sensor.tv_samsung_8_series_65_media_playback_status
State: 	unknown

sensor.tv_samsung_8_series_65_tv_channel
State:

sensor.tv_samsung_8_series_65_volume
State: 15

Attributes:
unit_of_measurement: %

switch.tv_samsung_8_series_65
State: on
```
**Test#2:**
Commented out "protocol: ws" from configuration.yaml to force "default ctl protocol".

Sensors and switch seem to work the same.  Improvement with "media_player.samsung_tv_remote" renders correctly (shows all options/buttons), but does not function. Source dropdown is populated with my HDMI1/HDMI2 values but doesn't do anything.  If I try to power off I get the following:

```
Log Details (ERROR)
Wed Jan 29 2020 14:44:18 GMT-0500 (Eastern Standard Time)
{'event': 'ms.channel.timeOut'}
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 201, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 335, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 357, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 287, in turn_off
    self.get_remote().close()
  File "/config/custom_components/samsungtv_custom/media_player.py", line 204, in get_remote
    self._remote = self._remote_class(self._config)
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/samsungctl/remote.py", line 11, in __init__
    self.remote = RemoteWebsocket(config)
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/samsungctl/remote_websocket.py", line 30, in __init__
    self._read_response()
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/samsungctl/remote_websocket.py", line 72, in _read_response
    raise exceptions.UnhandledResponse(response)
samsungctl.exceptions.UnhandledResponse: {'event': 'ms.channel.timeOut'}
```
**Test#3:**
Tried "protocol: ctl_beta":

Get this on restart:
```
Log Details (ERROR)
Wed Jan 29 2020 14:48:27 GMT-0500 (Eastern Standard Time)
Error while setting up platform samsungtv_custom
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 145, in setup_platform
    add_entities([SamsungTVDevice(host, port, name, timeout, mac, uuid, sourcelist, protocol)])
  File "/config/custom_components/samsungtv_custom/media_player.py", line 158, in __init__
    from .samsungctl_080b import exceptions
  File "/config/custom_components/samsungtv_custom/samsungctl_080b/__init__.py", line 15, in <module>
    from .remote import Remote  # NOQA
  File "/config/custom_components/samsungtv_custom/samsungctl_080b/remote.py", line 6, in <module>
    from .remote_legacy import RemoteLegacy
  File "/config/custom_components/samsungtv_custom/samsungctl_080b/remote_legacy.py", line 11, in <module>
    from . import upnp
  File "/config/custom_components/samsungtv_custom/samsungctl_080b/upnp/__init__.py", line 6, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

**Test#4**
For giggles, tried "protocol: ctl_qled" with port 8001:
No error on startup and the "media_player.samsung_tv_remote" renders correctly, a default source of TV/HDMI was set (instead of blank) but trying to do anything doesn't work.  State correctly shows "on" and more attributes are shown in Dev Tool with this protocol than with ws or ctl.

```
media_player.samsung_tv_remote
State: on	

Attributes:
source_list: TV/HDMI,FIOS,AcePC
volume_level: 0
is_volume_muted: false
source: TV/HDMI
friendly_name: Samsung TV Remote
supported_features: 20409
```

Yet the "sensor.tv volume" still shows 15 (so they don't agree)

Trying to turn off power yields same "samsungctl.exceptions.UnhandledResponse: {'event': 'ms.channel.timeOut'}" as above.

**Comment by ronsum232** [comment]
Likely you need `protocol: ctl_qled` but with `port: 8002`

**Comment by reefland** [comment]
> Likely you need `protocol: ctl_qled` but with `port: 8002`

Seems worse when I try port 8002. It does not even accurately show TV is ON or OFF with port 8002, whereas with port 8001 it does (as shown in Test #4 above).

> Also, you may verify that you are using lists '{ }' where necessary. Follow the examples closely.

My configuration.yaml part is included in original post and its using lists '{ }' which seem to follow the examples.  Sorry, I don't see something that is not consistent with the examples.
