### ISSUE TITLE
Errors after update HA to 0.112

### ISSUE THREAD

**Issue by avbor** [roberodin/ha-samsungtv-custom#49]
After update HA to v 0.112 i got a lot of errors:
ровень: ERROR
Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_custom/media_player.py:233
First occurred: 11:20:55 (3 occurrences)
Last logged: 11:20:55

Update for media_player.samsungtv_ue40c5100 fails
Update for media_player.samsungtv_ue32es5500 fails
Update for media_player.samsungtv_ue46es5507 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 227, in update
    self.send_key("KEY")
  File "/config/custom_components/samsungtv_custom/media_player.py", line 248, in send_key
    control_result = self.get_remote().control(key)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 233, in get_remote
    self._remote = self._remote_class(self._config)
  File "/usr/local/lib/python3.7/site-packages/samsungctl/remote.py", line 13, in __init__
    raise exceptions.UnknownMethod()
samsungctl.exceptions.UnknownMethod

![image](https://user-images.githubusercontent.com/32452033/86448557-959dbd00-bd1f-11ea-900a-e84fcdb8eea1.png)

TVs configured like this:
- platform: samsungtv_custom
  name: SamsungTV-UE40C5100
  host: <ip>
  port: 5601
  mac: <mac>
- platform: samsungtv_custom
  name: SamsungTV-UE32ES5500
  host: <ip>
  mac: <mac>
- platform: samsungtv_custom
  name: SamsungTV-UE46ES5507
  host: <ip>
  mac: <mac>

**Comment by megapearl** [comment]
Same problem here. I'm on Homeassistant 0.112.4

```
Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_custom/media_player.py:233
First occurred: July 14, 2020, 8:31:48 PM (17466 occurrences)
Last logged: 10:52:51 PM

Update for media_player.livingroom_television fails
Update for media_player.livingroom_bluray_player fails
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/opt/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 227, in update
    self.send_key("KEY")
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 248, in send_key
    control_result = self.get_remote().control(key)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 233, in get_remote
    self._remote = self._remote_class(self._config)
  File "/opt/homeassistant/lib/python3.7/site-packages/samsungctl/remote.py", line 13, in __init__
    raise exceptions.UnknownMethod()
samsungctl.exceptions.UnknownMethod
```

**Comment by ulnic** [comment]
Also having the same issue:

```
Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_custom/media_player.py:233
First occurred: 2:33:49 PM (43 occurrences)
Last logged: 2:41:31 PM

Update for media_player.samsung_tv_remote fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 227, in update
    self.send_key("KEY")
  File "/config/custom_components/samsungtv_custom/media_player.py", line 248, in send_key
    control_result = self.get_remote().control(key)
  File "/config/custom_components/samsungtv_custom/media_player.py", line 233, in get_remote
    self._remote = self._remote_class(self._config)
  File "/usr/local/lib/python3.7/site-packages/samsungctl/remote.py", line 13, in __init__
    raise exceptions.UnknownMethod()
samsungctl.exceptions.UnknownMethod
```

**Comment by ImNightwing** [comment]
Same issue here. Same stacktrace. Seems like the "encrypted" method in the configs is what's causing it.

**Comment by Bsunshine18** [comment]
First I would like to thank you for the effort you have gone to @roberodin - I know developing these custom components is not easy.

I am having the same issue as above - my setup is as follows:

- HA: HassOS 4.12
- HACS: v1.5.2
- ha-samsuntv-custom: 3.0.5

Note: I also have the standard Samsung TV integration installed and confirmed the TVs work (on/off, volume up/down, etc) 

I have created the devices as per below:

![image](https://user-images.githubusercontent.com/64714382/91055984-b7a12500-e668-11ea-8235-f6d3b01a59a9.png)

with each having the custom dropdown displaying correctly (such as below)

![image](https://user-images.githubusercontent.com/64714382/91053505-419bbe80-e666-11ea-8ac1-4fbc6b708b32.png)

As you can see unfortunately the state of all three TV is "unknown" and none of the functionality actually works. EG - clicking the power button cause a pop up error "Failed to call service media.player/turn_on"

Log details after restart of HA look as follows (same as the above):

![image](https://user-images.githubusercontent.com/64714382/91056187-fb942a00-e668-11ea-9c84-425bc7ac9ccc.png)

I do really like this component - I hope you'll be able to fix the issue soon.

Thanks
